const casess = {
  GET_NOTE_SUCCESS: "GET_NOTE_SUCCESS",
  ADD_NOTE_REQUEST: " ADD_NOTE_REQUEST",
  REMOVE_NOTE_REQUEST: "REMOVE_NOTE_REQUEST",
  REMOVE_NOTE_SUCCESS: "REMOVE_NOTE_SUCCESS",
};

export default casess;
