import type { NextPage } from 'next'
import Head from 'next/head'
import HomePage from '../components/HomePage'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Note TS</title>
        <meta name="description" content="Generated by create next app And TS+Saga" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  )
}

export default Home
